version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: finance
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - finance_data:/var/lib/postgresql/data
volumes:
  finance_data:
  